# Generated by Django 5.1.4 on 2026-05-08 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_department_to_user'),
        ('enrollment', '0008_subject_subject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_students', to='enrollment.program'),
        ),
        migrations.AddField(
            model_name='user',
            name='year_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_members', to='enrollment.department'),
        ),
    ]
