# Generated by Django 5.1.4 on 2026-09-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_add_program_year_level_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('registrar', 'Registrar'), ('department_encoder', 'Department Encoder'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
