# Generated by Django 5.1.4 on 2026-09-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_registration_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_placeholder',
            field=models.BooleanField(default=False),
        ),
    ]
