# Generated by Django 5.1.4 on 2026-09-18 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_is_placeholder'),
        ('enrollment', '0016_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='enrollment.curriculum'),
        ),
    ]
