# Generated by Django 5.1.4 on 2026-09-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_gec_faculty',
            field=models.BooleanField(default=False),
        ),
    ]
