# Generated by Django 5.1.4 on 2026-09-21 12:02

from django.db import migrations, models


def delete_encoder_accounts(apps, schema_editor):
    """The 'department_encoder' role is removed from the system; delete any
    accounts still holding it before the choice is dropped."""
    User = apps.get_model('authentication', 'User')
    User.objects.filter(role='department_encoder').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_is_gec_faculty'),
    ]

    operations = [
        migrations.RunPython(delete_encoder_accounts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('registrar', 'Registrar'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
