# Generated by Django 5.1.4 on 2026-10-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, choices=[('COS', 'COS'), ('Instructor I', 'Instructor I'), ('Instructor II', 'Instructor II'), ('Instructor III', 'Instructor III'), ('Assistant Professor I', 'Assistant Professor I'), ('Assistant Professor II', 'Assistant Professor II'), ('Assistant Professor III', 'Assistant Professor III'), ('Assistant Professor IV', 'Assistant Professor IV'), ('Associate Professor I', 'Associate Professor I'), ('Associate Professor II', 'Associate Professor II'), ('Associate Professor III', 'Associate Professor III'), ('Associate Professor IV', 'Associate Professor IV'), ('Associate Professor V', 'Associate Professor V'), ('Professor I', 'Professor I'), ('Professor II', 'Professor II'), ('Professor III', 'Professor III'), ('Professor IV', 'Professor IV'), ('Professor V', 'Professor V'), ('Professor VI', 'Professor VI')], default='', max_length=40),
        ),
    ]
