# Generated by Django 5.1.4 on 2026-09-18 01:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0015_alter_blockexpansionrequest_id_and_more'),
        ('grades', '0003_teachingassignment_block'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachingassignment',
            options={'ordering': ['-academic_term__year', 'subject__code', 'section']},
        ),
        migrations.AlterUniqueTogether(
            name='teachingassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='section',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='teachingassignment',
            unique_together={('faculty', 'subject', 'academic_term', 'section')},
        ),
    ]
