# Generated by Django 5.1.4 on 2026-09-20 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_stage_flags(apps, schema_editor):
    """Grades submitted under the old single is_submitted flag were fully finalised:
    mark both stages submitted so they stay visible and locked."""
    GradeRecord = apps.get_model('grades', 'GradeRecord')
    GradeRecord.objects.filter(is_submitted=True).update(
        midterm_submitted=True,
        final_submitted=True,
    )
    for r in GradeRecord.objects.filter(is_submitted=True, submitted_at__isnull=False):
        GradeRecord.objects.filter(pk=r.pk).update(
            midterm_submitted_at=r.submitted_at,
            final_submitted_at=r.submitted_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_alter_teachingassignment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='graderecord',
            name='final_is_inc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='final_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='final_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='is_dropped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='midterm_is_inc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='midterm_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='midterm_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MidtermReopenRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midterm_reopen_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_midterm_reopen_requests', to=settings.AUTH_USER_MODEL)),
                ('teaching_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midterm_reopen_requests', to='grades.teachingassignment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(backfill_stage_flags, migrations.RunPython.noop),
    ]
