# Generated by Django 5.1.4 on 2026-09-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_building_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('lecture', 'Lecture room'), ('laboratory', 'Laboratory')], default='lecture', max_length=20),
        ),
    ]
