# Generated by Django 5.1.4 on 2026-10-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='room',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
