# Generated by Django 5.1.4 on 2026-10-08 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_alter_classschedule_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_date', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipients', models.PositiveIntegerField(default=0)),
                ('class_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='schedules.classschedule')),
            ],
            options={
                'indexes': [models.Index(fields=['occurrence_date'], name='schedules_c_occurre_791360_idx')],
                'unique_together': {('class_schedule', 'occurrence_date')},
            },
        ),
    ]
