# Generated by Django 5.1.4 on 2026-05-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_department_subject_year_level_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', '1st Semester'), ('second', '2nd Semester'), ('summer', 'Summer')], max_length=10, null=True),
        ),
    ]
