# Generated by Codex on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_alter_subject_units_curriculumdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='units',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
