# Generated by Django 5.1.4 on 2026-05-08 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0008_subject_subject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentrequest',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_requests', to='enrollment.program'),
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_level', models.PositiveSmallIntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')])),
                ('name', models.CharField(max_length=20)),
                ('capacity', models.PositiveSmallIntegerField(default=30)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='enrollment.academicterm')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='enrollment.program')),
            ],
            options={
                'ordering': ['program', 'year_level', 'name'],
                'unique_together': {('program', 'academic_term', 'year_level', 'name')},
            },
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_requests', to='enrollment.block'),
        ),
    ]
