# Generated by Django 5.1.4 on 2026-09-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0019_seed_site_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicterm',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
