# Generated by Django 5.1.4 on 2026-09-30 19:49

from django.db import migrations, models

# Map the old enrollment student types onto the new four.
REMAP = {
    'freshman': 'new',
    'regular': 'continuing',
    'shiftee': 'transferee',
    '': 'continuing',
}


def forwards(apps, schema_editor):
    EnrollmentRequest = apps.get_model('enrollment', 'EnrollmentRequest')
    for old, new in REMAP.items():
        EnrollmentRequest.objects.filter(student_type=old).update(student_type=new)


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0021_hero_content_clear_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='student_type',
            field=models.CharField(blank=True, choices=[('new', 'New Student'), ('transferee', 'Transferee'), ('returnee', 'Returnee'), ('continuing', 'Continuing')], default='continuing', max_length=20),
        ),
        migrations.RunPython(forwards, backwards),
    ]
