# Generated by Django 5.1.4 on 2026-09-30 23:56

from django.db import migrations, models


def forwards(apps, schema_editor):
    PendingEnrollment = apps.get_model('enrollment', 'PendingEnrollment')
    PendingEnrollment.objects.filter(student_type='freshman').update(student_type='new')


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0022_alter_enrollmentrequest_student_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingenrollment',
            name='student_type',
            field=models.CharField(choices=[('new', 'New Student'), ('transferee', 'Transferee'), ('returnee', 'Returnee')], max_length=20),
        ),
        migrations.RunPython(forwards, backwards),
    ]
