# Generated by Django 5.1.4 on 2026-10-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0024_sync_current_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('program', 'code'), name='uniq_subject_program_code'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('program__isnull', True)), fields=('code',), name='uniq_subject_code_when_no_program'),
        ),
    ]
