# Generated by Django 5.1.4 on 2026-10-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0025_alter_subject_code_subject_uniq_subject_program_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingenrollment',
            name='assigned_student_id',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
